on: [push, workflow_dispatch]

name: build

jobs:

  ko-publish:
    name: Release ko artifact
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write  # undocumented OIDC support.
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20.x'
    - uses: ko-build/setup-ko@v0.6
    - run: ko build
    - uses: sigstore/cosign-installer@main
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: KO_DOCKER_REPO=ghcr.io/dkourkouzelis/hello-ko ko publish --bare github.com/dkourkouzelis/hello-ko
    - name: Sign
      run: COSIGN_EXPERIMENTAL=1 cosign sign -a git_sha=$GITHUB_SHA ghcr.io/dkourkouzelis/hello-ko
